#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: the ten steps that connect Kage's Main Menu to Google and WakaTime.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

MENU="http://127.0.0.1:8000"
API="$MENU/api/main_menu"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
EMAIL_DIR="$REPO_ROOT/Main_Menu/Backend/Email_Data"
CAL_DIR="$REPO_ROOT/Main_Menu/Backend/Calendar_Data"

# to_unix_path turns a pasted Windows path into one Git Bash can open.
# Handles surrounding quotes, backslashes and the C: drive prefix.
to_unix_path() {
  local p="$1"
  p="${p%\"}"
  p="${p#\"}"
  p="${p//\\//}"
  if [[ "$p" =~ ^([A-Za-z]):/(.*)$ ]]; then
    local drive="${BASH_REMATCH[1]}"
    p="/$(printf '%s' "$drive" | tr '[:upper:]' '[:lower:]')/${BASH_REMATCH[2]}"
  fi
  printf '%s' "$p"
}

# newest_download prints the most recent client_secret*.json in Downloads.
newest_download() {
  local dl="$HOME/Downloads"
  [[ -d "$dl" ]] || return 1
  ls -t "$dl"/client_secret*.json 2>/dev/null | head -n1
}

# state_of URL pulls the "state" field out of one of the card endpoints
# without needing jq on the box.
state_of() {
  curl -s --max-time 20 "$1" \
    | grep -o '"state"[[:space:]]*:[[:space:]]*"[^"]*"' \
    | head -n1 \
    | sed 's/.*"\([^"]*\)"$/\1/'
}

# install_client_json DEST_DIR DEST_NAME LABEL
# Offers the newest Downloads match, else asks for a path; checks the file
# really is a Desktop OAuth client before copying it into place.
install_client_json() {
  local dest_dir="$1" dest_name="$2" label="$3"
  local dest="$dest_dir/$dest_name" guess="" src=""

  if [[ -f "$dest" ]]; then
    note "$label credentials are already in place."
    confirm "Replace them with a freshly downloaded file?" || return 0
  fi

  guess="$(newest_download || true)"
  if [[ -n "$guess" ]]; then
    note "newest download: $guess"
    if confirm "Use that file?"; then src="$guess"; fi
  fi

  while [[ -z "$src" || ! -f "$src" ]]; do
    ask CLIENT_JSON_PATH "Full path to the downloaded JSON:"
    src="$(to_unix_path "$CLIENT_JSON_PATH")"
    [[ -f "$src" ]] || warn "no file at: $src"
  done

  if ! grep -q '"installed"' "$src"; then
    warn "that file has no installed section, so it is not a Desktop client."
    note "Re-download from Credentials, choosing application type: Desktop app."
    SKIPPED+=("$label credentials (wrong client type downloaded)")
    return 0
  fi

  mkdir -p "$dest_dir"
  cp "$src" "$dest"
  printf '  %s✓ installed%s %s\n' "$GREEN" "$RESET" "$dest"
}

# menu_up checks the Main Menu is serving before we poke its API.
menu_up() { curl -s -o /dev/null --max-time 4 "$API/navigation"; }

banner "Kage · connect Gmail, Google Calendar and WakaTime"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight: is the Main Menu running?"
say "Both consent flows are triggered through the Main Menu's own API,"
say "so it has to be up on port 8000 before we start."
if menu_up; then
  printf '  %s✓%s the Main Menu is answering on %s\n' "$GREEN" "$RESET" "$MENU"
else
  warn "nothing is answering on $MENU"
  say "Open a second terminal at the repo root and run:"
  note "  .venv/Scripts/python Start_Inky/start_every_screen.py"
  pause "Press Enter once it prints RUNNING."
  if ! menu_up; then
    warn "still not answering. Fix that first, then re-run this wizard."
    exit 1
  fi
  printf '  %s✓%s the Main Menu is answering now\n' "$GREEN" "$RESET"
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: one project for both cards"
say "One project covers Gmail and Calendar. If you already made one for"
say "either card, reuse it here rather than making a second."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it something you will recognise, e.g. kage-local."
step "Create it, then check it is the project selected in the top bar."
pause "Press Enter when the project is created and selected."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Enable the two APIs"
say "A project cannot call an API it has not enabled. Two to turn on."
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com"
step "Press ENABLE on the Gmail API page that just opened."
pause "Press Enter once Gmail API says it is enabled."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
step "Press ENABLE on the Google Calendar API page."
pause "Press Enter once Calendar API says it is enabled."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "OAuth consent screen"
say "This is who the app says it is when it asks you for permission."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "User type: EXTERNAL. Internal is only for Workspace organisations."
step "App name: anything, e.g. Kage. Support email: your own address."
step "Developer contact: your own address. Save and continue."
step "Scopes page: add nothing here. Save and continue."
step "Test users: ADD USERS, add YOUR OWN Google address, save."
warn "Leave it in Testing. Publishing is for apps with other people's users."
note "A test-mode refresh token expires after 7 days; re-run this to renew."
pause "Press Enter when the consent screen is saved."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Create the Desktop OAuth client"
say "One Desktop client is enough for both cards: they keep separate"
say "tokens with separate scopes, so revoking one never breaks the other."
open_url "https://console.cloud.google.com/apis/credentials"
step "CREATE CREDENTIALS → OAuth client ID."
step "Application type: DESKTOP APP. Not Web: the loopback ports matter."
step "Name it Kage desktop, then CREATE."
step "In the dialog, press DOWNLOAD JSON. Leave the file in Downloads."
pause "Press Enter once the JSON is downloaded."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Install the Gmail credentials"
say "The Email card polls for this exact file and wakes up on its own"
say "within a minute of it appearing. No restart needed."
install_client_json "$EMAIL_DIR" "gmail_credentials.json" "Gmail"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Authorise Gmail (read-only)"
say "Scope: gmail.readonly. It cannot send, reply or delete."
if [[ ! -f "$EMAIL_DIR/gmail_credentials.json" ]]; then
  warn "no Gmail credentials in place, so skipping the consent."
  SKIPPED+=("Gmail consent (credentials were not installed)")
else
  say "A Google tab will open on port 8788. Approve it there."
  warn "Google will say the app is unverified. That is expected for your own"
  note "  Desktop client in Testing mode. Advanced → Go to (your app name)."
  curl -s -X POST "$API/email/connect" >/dev/null || true
  pause "Press Enter once you have finished approving in the browser."
  EMAIL_STATE="$(state_of "$API/email/summary")"
  if [[ "$EMAIL_STATE" == "ok" ]]; then
    printf '  %s✓ Gmail connected%s\n' "$GREEN" "$RESET"
  else
    warn "the card still reports: ${EMAIL_STATE:-no answer}"
    note "Main_Menu/Backend/EMAIL_SETUP.md lists what each state means."
    SKIPPED+=("Gmail consent (card state: ${EMAIL_STATE:-unknown})")
  fi
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Install the Calendar credentials"
say "The same downloaded client works. The two cards keep separate tokens"
say "on purpose, so revoking one never breaks the other."
if [[ -f "$EMAIL_DIR/gmail_credentials.json" ]] && confirm "Reuse the same client JSON for Calendar?"; then
  mkdir -p "$CAL_DIR"
  cp "$EMAIL_DIR/gmail_credentials.json" "$CAL_DIR/calendar_credentials.json"
  printf '  %s✓ installed%s %s\n' "$GREEN" "$RESET" "$CAL_DIR/calendar_credentials.json"
else
  install_client_json "$CAL_DIR" "calendar_credentials.json" "Calendar"
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Authorise Google Calendar (read + write)"
say "Scope: calendar.events. It reads your events, and creates the ones"
say "you approve in a day popover. Writing is what reaches your phone."
if [[ ! -f "$CAL_DIR/calendar_credentials.json" ]]; then
  warn "no Calendar credentials in place, so skipping the consent."
  SKIPPED+=("Calendar consent (credentials were not installed)")
else
  say "A second Google tab will open, this time on port 8789."
  curl -s -X POST "$API/calendar/connect" >/dev/null || true
  pause "Press Enter once you have finished approving in the browser."
  CAL_STATE="$(state_of "$API/calendar/month")"
  if [[ "$CAL_STATE" == "ok" ]]; then
    printf '  %s✓ Calendar connected%s\n' "$GREEN" "$RESET"
    note "The agent still only PROPOSES events. Nothing reaches your calendar"
    note "until you press Add to calendar in a day's popover."
  else
    warn "the card still reports: ${CAL_STATE:-no answer}"
    note "Main_Menu/Backend/CALENDAR_SETUP.md lists what each state means."
    SKIPPED+=("Calendar consent (card state: ${CAL_STATE:-unknown})")
  fi
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "WakaTime API key (optional)"
say "This fills the WAKA half of the Calendar card's switch, and the amber"
say "tint on each day cell. Skip it and everything else still works."
if confirm "Add a WakaTime API key now?"; then
  open_url "https://wakatime.com/settings/api-key"
  step "Copy the API key shown there."
  warn "Use the API KEY, not an app secret. If you ever pasted an app secret"
  note "  into a chat or a log, revoke it at https://wakatime.com/apps."
  ask_secret WAKATIME_KEY "Paste the WakaTime API key:"
  if [[ -n "${WAKATIME_KEY:-}" ]]; then
    mkdir -p "$CAL_DIR"
    printf '{\n  "api_key": "%s"\n}\n' "$WAKATIME_KEY" > "$CAL_DIR/wakatime.json"
    printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$CAL_DIR/wakatime.json"
    WAKA_STATE="$(state_of "$API/wakatime/summary")"
    if [[ "$WAKA_STATE" == "ok" ]]; then
      printf '  %s✓ WakaTime connected%s\n' "$GREEN" "$RESET"
      note "On the free plan only 7 days are readable, so Kage snapshots them"
      note "every sync: your local history grows from today onward."
    else
      warn "WakaTime reports: ${WAKA_STATE:-no answer}"
      SKIPPED+=("WakaTime key (card state: ${WAKA_STATE:-unknown})")
    fi
  fi
else
  SKIPPED+=("WakaTime API key (skipped on purpose)")
fi

finish
note "Open $MENU and check the CALENDAR and EMAIL cards."
note "Docs: Main_Menu/Backend/EMAIL_SETUP.md and CALENDAR_SETUP.md"
printf '\n'
